correct install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -4,36 +4,16 @@
 #
 # Install project dependencies and packages
 
-# Stop on errors, undefined variables, and errors in pipelines
+# Stop on errors, print commands
+# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
 set -Eeuo pipefail
+set -x
 
-# Change to the directory containing this script
-cd "$(dirname "${BASH_SOURCE[0]}")"/..
-
-# Create virtual environment if it doesn't exist
-if [ ! -d "env" ]; then
-  echo "+ python3 -m venv env"
-  python3 -m venv env
-else
-  echo "Virtual environment already exists"
-fi
-
-# Activate virtual environment
-echo "+ source env/bin/activate"
-# shellcheck disable=SC1091
+python3 -m venv env
 source env/bin/activate
-
-# Install requirements
-echo "+ pip install -r requirements.txt"
 pip install -r requirements.txt
 
-# Install index_server package in editable mode
-echo "+ pip install -e index_server"
 pip install -e index_server
-
-# Install search_server package in editable mode
-echo "+ pip install -e search_server"
 pip install -e search_server
 
 echo "Installation complete!"
-
